version: '2'
services:

    # Application container
    php:
        container_name: exposeapi_php
        build: .
        restart: unless-stopped
        volumes:
            - ./:/server/http
        ports:
            - "80:80"
            - "443:443"
        links:
            - redis
        environment:
            DEBUG: 'true'

    redis:
        container_name: exposeapi_redis
        image: sickp/alpine-redis:3.2.2
        restart: unless-stopped
        ports:
            - "6379:6379"

